(part "AP1509-50SG-13"
    (packageRef "SOIC127P600X170-8N")
    (interface
        (port "1" (symbPinId 1) (portName "VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OUTPUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "FB") (portType INOUT))
        (port "4" (symbPinId 4) (portName "SD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "GND_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "GND_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Manufacturer_Name" "Diodes Incorporated")
    (property "Manufacturer_Part_Number" "AP1509-50SG-13")
    (property "Mouser_Part_Number" "621-AP1509-50SG-13")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Diodes-Incorporated/AP1509-50SG-13?qs=EJYhozv%252BYpwbI10CpTvwPw%3D%3D")
    (property "Arrow_Part_Number" "AP1509-50SG-13")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ap1509-50sg-13/diodes-incorporated.html?utm_currency=USD&region=nac")
    (property "Description" "DiodesZetex, AP1509-50SG-13 DC-DC Converter 2A 8-Pin, SOP")
    (property "Datasheet_Link" "https://www.diodes.com//assets/Datasheets/AP1509.pdf")
    (property "symbolName1" "AP1509-50SG-13")
)
