* Model BEMF del motor BLDC (LSE-I). Font: apunts 'Modelat d'un motor BLDC'
.subckt BEMF A B C N THETA_T WANG HA HB HC KT=15e-3
* resistencia de terminacio del senyal WANG
R1 WANG 0 10MEG
* resistencia de terminacio del senyal THETA_T
R2 THETA_T 0 10MEG
* calcul de l'angle [0, 2*pi]
ETHETA THETA 0 value = { (V(THETA_T) / (2*pi) - floor(V(THETA_T) / (2*PI)) ) * 2*pi }
R3 THETA 0 10MEG
* tensions de BEMF
EA A N value = { {KT} * V(WANG) * sin(V(THETA)) }
EB B N value = { {KT} * V(WANG) * sin(V(THETA) + 2*pi/3) }
EC C N value = { {KT} * V(WANG) * sin(V(THETA) + 4*pi/3) }
* sensors hall
EAB HA 0 value = { if((V(A) - V(B)) > 0, 5, 0)}
EBC HB 0 value = { if((V(B) - V(C)) > 0, 5, 0)}
ECA HC 0 value = { if((V(C) - V(A)) > 0, 5, 0)}
.ends BEMF
